version: '3.7'
services:
  api:
    container_name: test-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./src:/var/www/src
    restart: always
    ports:
      - "3000:3000"
  mysql:
      image: mysql:8
      container_name: test-mysql
      restart: always
      volumes:
        - ./mysqlDB:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=256M
      environment:
        MYSQL_DATABASE: test_database
        MYSQL_USER: test_user
        MYSQL_PASSWORD: test_password
        MYSQL_ROOT_PASSWORD: test_root_password
      ports:
        - "3308:3308"



